runtime: nodejs
env: flex
service: sample-config-service
handlers:
  - url: /
    static_dir: /
    http_headers:
      Access-Control-Allow-Origin: '*'
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10
  volumes:
    - name: ramdisk1
      volume_type: tmpfs
      size_gb: 0.5
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 15
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.6
network:
  name: >-
    projects/project-4d333270/global/networks/google-managed-services-vpc-network
  subnetwork_name: google-managed-services-subnet-us-west2-10-26-24-0-slash-22
beta_settings:
  cloud_sql_instances: 'sanm-gcp-forecast-uat:us-west2:sanm-forecast-uat-pg'
