runtime: nodejs
  #nodejs/custom
env: flex
# api_version: 1

#  secure: always
#[module name]
service: sample-config-service

#endpoints_api_service:
  # The following values are to be replaced by information from the output of
  # 'gcloud endpoints services deploy openapi-appengine.yaml' command.
#  name: API_HOST
#  rollout_strategy: managed
  #allowCors: true


handlers:
- url: /
  static_dir: /
  http_headers:
    Access-Control-Allow-Origin: '*'
    
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10
  volumes:
  - name: ramdisk1
    volume_type: tmpfs
    size_gb: 0.5

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 15
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.6

network:
  name: projects/project-4d333270/global/networks/google-managed-services-vpc-network
  subnetwork_name: google-managed-services-subnet-us-west2-10-26-24-0-slash-22

# [START env]
#env_variables:
 # SQL_USER: fb31847639b603f894a3dfe38e
 # SQL_PASSWORD: db3184762dba1baef9f49e
 # SQL_DATABASE: shipping_supply
  # e.g. my-awesome-project:us-central1:my-cloud-sql-instance
  #INSTANCE_CONNECTION_NAME: sanm-gcp-shipping-dev:us-west1:sanm-shippingdev-pg
  #INSTANCE_CONNECTION_NAME: sanm-gcp-shipping-dev:us-west1:sanm-shipping-supply-dev-pg
  #NODE_ENV: production
# [END env]


#network:
#  instance_tag: sanm-gcp-shipping-dev
#  name: shipping-dev
#  subnetwork_name: shipping-dev
  #forwarded_ports:
   # - PORT
   # - HOST_PORT:CONTAINER_PORT
   # - PORT/tcp
   # - HOST_PORT:CONTAINER_PORT/udp

#health_check:
  #enable_health_check: false
#  check_interval_sec: 5
#  timeout_sec: 4
#  unhealthy_threshold: 2
#  healthy_threshold: 2


# [START cloudsql_settings]
beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
 # cloud_sql_instances: sanm-gae-appsdev2:us-central1:new-mysql-instance
 cloud_sql_instances: sanm-gcp-forecast-uat:us-west2:sanm-forecast-uat-pg
# [END cloudsql_settings]
